# Generated by Django 6.0.1 on 2026-07-26 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cast_member_app', '0001_initial'),
        ('category_app', '0001_initial'),
        ('genre_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('launch_year', models.IntegerField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('published', models.BooleanField(default=False)),
                ('rating', models.CharField(choices=[('ER', 'ER'), ('L', 'L'), ('AGE_10', 'AGE_10'), ('AGE_12', 'AGE_12'), ('AGE_14', 'AGE_14'), ('AGE_16', 'AGE_16'), ('AGE_18', 'AGE_18')], max_length=20)),
                ('cast_members', models.ManyToManyField(related_name='videos', to='cast_member_app.castmember')),
                ('categories', models.ManyToManyField(related_name='videos', to='category_app.category')),
                ('genres', models.ManyToManyField(related_name='videos', to='genre_app.genre')),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
