# Generated by Django 6.0.1 on 2026-08-16 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioVideoMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('raw_location', models.CharField(max_length=255)),
                ('encoded_location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('ERROR', 'ERROR')], default='PENDING', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('raw_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='trailer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_trailer', to='video_app.audiovideomedia'),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_media', to='video_app.audiovideomedia'),
        ),
        migrations.AddField(
            model_name='video',
            name='banner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video_app.imagemedia'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail', to='video_app.imagemedia'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_half',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail_half', to='video_app.imagemedia'),
        ),
    ]
