# Generated by Django 6.0.1 on 2026-09-07 00:00

from django.db import migrations, models


def populate_media_type(apps, schema_editor):
    AudioVideoMedia = apps.get_model('video_app', 'AudioVideoMedia')
    Video = apps.get_model('video_app', 'Video')

    trailer_ids = set(
        Video.objects.exclude(trailer_id__isnull=True).values_list('trailer_id', flat=True)
    )

    for media in AudioVideoMedia.objects.all().iterator():
        media.media_type = 'TRAILER' if media.id in trailer_ids else 'VIDEO'
        media.save(update_fields=['media_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_audiovideomedia_imagemedia_video_trailer_video_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovideomedia',
            name='media_type',
            field=models.CharField(
                choices=[('VIDEO', 'VIDEO'), ('TRAILER', 'TRAILER'), ('BANNER', 'BANNER'), ('THUMBNAIL', 'THUMBNAIL'), ('THUMBNAIL_HALF', 'THUMBNAIL_HALF')],
                max_length=20,
                null=True,
            ),
        ),
        migrations.RunPython(populate_media_type, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='audiovideomedia',
            name='media_type',
            field=models.CharField(
                choices=[('VIDEO', 'VIDEO'), ('TRAILER', 'TRAILER'), ('BANNER', 'BANNER'), ('THUMBNAIL', 'THUMBNAIL'), ('THUMBNAIL_HALF', 'THUMBNAIL_HALF')],
                max_length=20,
            ),
        ),
    ]